#!/usr/bin/env sh

export XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
export XDG_BIN_HOME=${XDG_BIN_HOME:-"$HOME/.local/bin"}
export XDG_LIB_HOME=${XDG_LIB_HOME:-"$HOME/.local/lib"}
export XDG_OPT_HOME=${XDG_OPT_HOME:-"$HOME/.local/opt"}
export XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}
export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-"$TMPDIR"}

export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-"/etc/xdg"}
export XDG_BIN_DIRS=${XDG_BIN_DIRS:-"/usr/local/bin:/usr/bin"}
export XDG_LIB_DIRS=${XDG_LIB_DIRS:-"/usr/local/lib:/usr/lib"}
export XDG_DATA_DIRS=${XDG_DATA_DIRS:-"/usr/local/share:/usr/share"}

export XDG_DESKTOP_DIR=${XDG_DESKTOP_DIR:-"$HOME/Desktop"}
export XDG_DOCUMENTS_DIR=${XDG_DOCUMENTS_DIR:-"$HOME/Documents"}
export XDG_DOWNLOAD_DIR=${XDG_DOWNLOAD_DIR:-"$HOME/Downloads"}
export XDG_MUSIC_DIR=${XDG_MUSIC_DIR:-"$HOME/Music"}
export XDG_PICTURES_DIR=${XDG_PICTURES_DIR:-"$HOME/Pictures"}
export XDG_PUBLICSHARE_DIR=${XDG_PUBLICSHARE_DIR:-"$HOME/Public"}
export XDG_TEMPLATES_DIR=${XDG_TEMPLATES_DIR:-"$HOME/Templates"}
export XDG_VIDEOS_DIR=${XDG_VIDEOS_DIR:-"$HOME/Videos"}

set -a
if [ -d "$XDG_CONFIG_HOME/shell/env.d/xdg.d/" ]; then
  for i in $XDG_CONFIG_HOME/shell/env.d/xdg.d/* ; do
    if [ -r $i ] ; then . $i ; fi
  done
  unset i
fi
set +a
